export enum ErrorKind {
    OFFLINE_UNAVAILABLE = "OFFLINE_UNAVAILABLE",
    UNKNOWN_ERROR = "UNKNOWN_ERROR",
    INVALID_SCENE = "INVALID_SCENE",
    DELETED_SCENE = "DELETED_SCENE",
    NOT_AUTHORIZED = "NOT_AUTHORIZED",
    LEGACY_BINARY_FORMAT = "LEGACY_BINARY_FORMAT",
}
