name: Production environment

on:
    #  release:
    #    types: [created]
    push:
        branches:
            - develop
        paths-ignore:
            - ".github/workflows/**"
    workflow_dispatch:
env:
    AZURE_WEBAPP_NAME: novorender-explorer # set this to your application's name
    AZURE_WEBAPP_SLOT: dev
    AZURE_WEBAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
    NODE_VERSION: "20.15.1" # set this to the node version to use

jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - name: npm install, build, and test
              run: |
                  # Build and test the project, then
                  # deploy to Azure Web App.
                  npm ci
                  npm run build --if-present
              # npm run test --if-present
            - name: Remove node modules
              run: |
                  rm -rf ./node_modules
            - name: Install server dependencies
              run: |
                  (cd server && npm ci && mv ./node_modules ../node_modules)
            - name: "Deploy to Azure WebApp"
              uses: azure/webapps-deploy@v2
              with:
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
                  slot-name: ${{ env.AZURE_WEBAPP_SLOT }}
